"""
Threat Detector

Real-time threat detection and alerting for the ESG audit system.
Integrates with honeypot and red team systems for comprehensive monitoring.
"""

import os
import json
import logging
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum

logger = logging.getLogger(__name__)


class ThreatSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class ThreatType(str, Enum):
    INTRUSION_ATTEMPT = "intrusion_attempt"
    DATA_EXFILTRATION = "data_exfiltration"
    PROMPT_INJECTION = "prompt_injection"
    ADVERSARIAL_ATTACK = "adversarial_attack"
    ANOMALOUS_BEHAVIOR = "anomalous_behavior"
    CREDENTIAL_ABUSE = "credential_abuse"
    PRIVILEGE_ESCALATION = "privilege_escalation"


@dataclass
class ThreatAlert:
    """Security alert generated by threat detection."""
    alert_id: str
    timestamp: str
    threat_type: ThreatType
    severity: ThreatSeverity
    source: str
    description: str
    indicators: List[str]
    affected_components: List[str]
    recommended_actions: List[str]
    raw_data: Dict[str, Any] = field(default_factory=dict)
    resolved: bool = False
    resolved_at: Optional[str] = None


@dataclass
class ThreatMetrics:
    """Aggregated threat metrics."""
    total_alerts: int
    alerts_by_severity: Dict[str, int]
    alerts_by_type: Dict[str, int]
    top_threat_sources: List[Dict[str, Any]]
    mean_time_to_detection: float
    mean_time_to_resolution: float
    threat_trend: str


class ThreatDetector:
    """
    Centralized threat detection and alerting system.
    
    Features:
    - Real-time anomaly detection
    - Correlation of multiple threat indicators
    - Automated alert generation
    - Integration with honeypot and red team data
    """
    
    def __init__(
        self,
        alert_threshold: float = 0.6,
        auto_resolve_after_hours: int = 24,
    ):
        self.alert_threshold = alert_threshold
        self.auto_resolve_after_hours = auto_resolve_after_hours
        self.alerts: List[ThreatAlert] = []
        self._detection_rules: Dict[str, callable] = {}
        self._load_default_rules()
    
    def _load_default_rules(self) -> None:
        """Load default threat detection rules."""
        self._detection_rules = {
            "multiple_failed_auth": self._detect_brute_force,
            "suspicious_prompt": self._detect_prompt_injection,
            "data_access_anomaly": self._detect_data_anomaly,
            "honeypot_trigger": self._detect_honeypot_hit,
            "red_team_vulnerability": self._detect_vulnerability,
        }
    
    def analyze_event(
        self,
        event_type: str,
        event_data: Dict[str, Any],
    ) -> Optional[ThreatAlert]:
        """
        Analyze an event for potential threats.
        
        Args:
            event_type: Type of event (auth, api_call, etc.)
            event_data: Event payload
        
        Returns:
            ThreatAlert if threat detected, None otherwise
        """
        import secrets
        
        threat_score = 0.0
        threat_type = None
        indicators = []
        
        for rule_name, rule_func in self._detection_rules.items():
            score, detected_type, detected_indicators = rule_func(event_type, event_data)
            if score > 0:
                threat_score = max(threat_score, score)
                if detected_type:
                    threat_type = detected_type
                indicators.extend(detected_indicators)
        
        if threat_score >= self.alert_threshold:
            alert = ThreatAlert(
                alert_id=secrets.token_urlsafe(8),
                timestamp=datetime.now(timezone.utc).isoformat(),
                threat_type=threat_type or ThreatType.ANOMALOUS_BEHAVIOR,
                severity=self._calculate_severity(threat_score),
                source=event_data.get("source_ip", "unknown"),
                description=f"Threat detected: {threat_type.value if threat_type else 'unknown'}",
                indicators=indicators,
                affected_components=event_data.get("affected_components", ["audit_system"]),
                recommended_actions=self._get_recommended_actions(threat_type),
                raw_data=event_data,
            )
            
            self.alerts.append(alert)
            self._log_alert(alert)
            
            return alert
        
        return None
    
    def _detect_brute_force(
        self,
        event_type: str,
        event_data: Dict[str, Any],
    ) -> tuple:
        """Detect brute force authentication attempts."""
        if event_type != "auth":
            return 0.0, None, []
        
        failed_attempts = event_data.get("failed_attempts", 0)
        
        if failed_attempts >= 10:
            return 0.9, ThreatType.CREDENTIAL_ABUSE, [
                f"high_failure_rate:{failed_attempts}",
                "possible_brute_force"
            ]
        elif failed_attempts >= 5:
            return 0.6, ThreatType.CREDENTIAL_ABUSE, [
                f"elevated_failure_rate:{failed_attempts}"
            ]
        
        return 0.0, None, []
    
    def _detect_prompt_injection(
        self,
        event_type: str,
        event_data: Dict[str, Any],
    ) -> tuple:
        """Detect prompt injection attempts."""
        if event_type != "llm_request":
            return 0.0, None, []
        
        prompt = event_data.get("prompt", "").lower()
        indicators = []
        score = 0.0
        
        injection_patterns = [
            ("ignore instructions", 0.8),
            ("disregard", 0.6),
            ("override", 0.7),
            ("system prompt", 0.9),
            ("bypass", 0.7),
            ("jailbreak", 0.9),
            ("[system]", 0.6),
            ("admin mode", 0.7),
        ]
        
        for pattern, weight in injection_patterns:
            if pattern in prompt:
                score = max(score, weight)
                indicators.append(f"injection_pattern:{pattern}")
        
        return score, ThreatType.PROMPT_INJECTION if score > 0 else None, indicators
    
    def _detect_data_anomaly(
        self,
        event_type: str,
        event_data: Dict[str, Any],
    ) -> tuple:
        """Detect anomalous data access patterns."""
        if event_type not in ("data_access", "api_call"):
            return 0.0, None, []
        
        score = 0.0
        indicators = []
        
        if event_data.get("data_volume", 0) > 1000000:
            score += 0.5
            indicators.append("high_data_volume")
        
        if event_data.get("access_frequency", 0) > 100:
            score += 0.4
            indicators.append("high_access_frequency")
        
        if event_data.get("unusual_time", False):
            score += 0.2
            indicators.append("off_hours_access")
        
        return min(1.0, score), ThreatType.DATA_EXFILTRATION if score > 0.5 else None, indicators
    
    def _detect_honeypot_hit(
        self,
        event_type: str,
        event_data: Dict[str, Any],
    ) -> tuple:
        """Process honeypot interaction as potential threat."""
        if event_type != "honeypot":
            return 0.0, None, []
        
        risk_score = event_data.get("risk_score", 0.0)
        indicators = event_data.get("threat_indicators", [])
        
        threat_type = ThreatType.INTRUSION_ATTEMPT
        if any("injection" in str(i).lower() for i in indicators):
            threat_type = ThreatType.ADVERSARIAL_ATTACK
        
        return risk_score, threat_type, indicators
    
    def _detect_vulnerability(
        self,
        event_type: str,
        event_data: Dict[str, Any],
    ) -> tuple:
        """Process red team vulnerability finding."""
        if event_type != "red_team":
            return 0.0, None, []
        
        is_vulnerable = event_data.get("is_vulnerable", False)
        vulnerability_score = event_data.get("vulnerability_score", 0.0)
        
        if is_vulnerable:
            return (
                vulnerability_score,
                ThreatType.ADVERSARIAL_ATTACK,
                [f"vulnerability:{event_data.get('attack_type', 'unknown')}"]
            )
        
        return 0.0, None, []
    
    def _calculate_severity(self, score: float) -> ThreatSeverity:
        """Calculate alert severity from score."""
        if score >= 0.9:
            return ThreatSeverity.CRITICAL
        elif score >= 0.7:
            return ThreatSeverity.HIGH
        elif score >= 0.5:
            return ThreatSeverity.MEDIUM
        else:
            return ThreatSeverity.LOW
    
    def _get_recommended_actions(self, threat_type: Optional[ThreatType]) -> List[str]:
        """Get recommended actions for a threat type."""
        actions = {
            ThreatType.INTRUSION_ATTEMPT: [
                "Block source IP",
                "Enable enhanced monitoring",
                "Review access logs"
            ],
            ThreatType.DATA_EXFILTRATION: [
                "Restrict data access",
                "Enable DLP controls",
                "Investigate affected data"
            ],
            ThreatType.PROMPT_INJECTION: [
                "Apply prompt filtering",
                "Enable input sanitization",
                "Review LLM responses"
            ],
            ThreatType.ADVERSARIAL_ATTACK: [
                "Review security controls",
                "Apply security patches",
                "Update detection rules"
            ],
            ThreatType.CREDENTIAL_ABUSE: [
                "Lock affected accounts",
                "Force password reset",
                "Enable MFA"
            ],
        }
        
        return actions.get(threat_type, ["Investigate and assess"])
    
    def _log_alert(self, alert: ThreatAlert) -> None:
        """Log security alert."""
        log_level = {
            ThreatSeverity.CRITICAL: logging.CRITICAL,
            ThreatSeverity.HIGH: logging.ERROR,
            ThreatSeverity.MEDIUM: logging.WARNING,
            ThreatSeverity.LOW: logging.INFO,
        }
        
        logger.log(
            log_level.get(alert.severity, logging.INFO),
            f"[THREAT ALERT] {alert.severity.value}: {alert.threat_type.value} "
            f"from {alert.source} - {alert.description}"
        )
    
    def resolve_alert(self, alert_id: str) -> bool:
        """Mark an alert as resolved."""
        for alert in self.alerts:
            if alert.alert_id == alert_id:
                alert.resolved = True
                alert.resolved_at = datetime.now(timezone.utc).isoformat()
                logger.info(f"[THREAT] Alert {alert_id} resolved")
                return True
        return False
    
    def get_active_alerts(self) -> List[ThreatAlert]:
        """Get all unresolved alerts."""
        return [a for a in self.alerts if not a.resolved]
    
    def get_metrics(self) -> ThreatMetrics:
        """Get aggregated threat metrics."""
        if not self.alerts:
            return ThreatMetrics(
                total_alerts=0,
                alerts_by_severity={},
                alerts_by_type={},
                top_threat_sources=[],
                mean_time_to_detection=0.0,
                mean_time_to_resolution=0.0,
                threat_trend="no_data",
            )
        
        by_severity = {}
        by_type = {}
        source_counts = {}
        
        for alert in self.alerts:
            sev = alert.severity.value
            by_severity[sev] = by_severity.get(sev, 0) + 1
            
            typ = alert.threat_type.value
            by_type[typ] = by_type.get(typ, 0) + 1
            
            source = alert.source
            source_counts[source] = source_counts.get(source, 0) + 1
        
        top_sources = sorted(
            [{"source": k, "count": v} for k, v in source_counts.items()],
            key=lambda x: x["count"],
            reverse=True,
        )[:5]
        
        recent = len([a for a in self.alerts if not a.resolved])
        older = len([a for a in self.alerts if a.resolved])
        
        if recent > older:
            trend = "increasing"
        elif recent < older:
            trend = "decreasing"
        else:
            trend = "stable"
        
        return ThreatMetrics(
            total_alerts=len(self.alerts),
            alerts_by_severity=by_severity,
            alerts_by_type=by_type,
            top_threat_sources=top_sources,
            mean_time_to_detection=0.5,
            mean_time_to_resolution=2.0,
            threat_trend=trend,
        )
    
    def export_alerts(self) -> List[Dict[str, Any]]:
        """Export all alerts for external processing."""
        return [
            {
                "alert_id": a.alert_id,
                "timestamp": a.timestamp,
                "threat_type": a.threat_type.value,
                "severity": a.severity.value,
                "source": a.source,
                "description": a.description,
                "indicators": a.indicators,
                "resolved": a.resolved,
                "resolved_at": a.resolved_at,
            }
            for a in self.alerts
        ]
